language: node_js
node_js:
- '10.15.0'
sudo: required
services:
- docker

before_install:
  - echo "//registry.lina.codes/:_authToken=\${NPM_TOKEN}" > ~/.npmrc
  - echo "registry=https://registry.npmjs.org/" >> ~/.npmrc
  - echo "@prtf:registry=https://registry.lina.codes/" >> ~/.npmrc

stages:
  - name: deploy
    if: env(TRAVIS_PULL_REQUEST) != true && branch = master

branches:
  only:
  - master
  - develop

install:
  - npm i -g @angular/cli
  - cd api
  - npm i
  - cd ../app
  - npm i
  - cd ..

before_deploy:
  - export GITHUB_USER=ragauskl:$GITHUB_TOKEN
  - git config --global user.email "$GITHUB_EMAIL"
  - git config --global user.name "$GITHUB_USER"
  - git config user.email "$GITHUB_EMAIL"
  - git config user.name "$GITHUB_USER"
  - git remote set-url origin https://$GITHUB_USER@github.com/ragauskl/portfolio.git

deploy:
  - cd app
  - npm run build
  - npm run deploy

