language: node_js
node_js:
- '13.7.0'
os: linux
services:
- docker

before_install:
  - npm -v
  - echo $TRAVIS_BRANCH
  - echo $TRAVIS_EVENT_TYPE
  - echo $TRAVIS_PULL_REQUEST
  - echo $TRAVIS_PULL_REQUEST_BRANCH
  - echo "//registry.lina.codes/:_authToken=\${NPM_TOKEN}" > ~/.npmrc
  - echo "registry=https://registry.npmjs.org/" >> ~/.npmrc
  - echo "@prtf:registry=https://registry.lina.codes/" >> ~/.npmrc
  - export GITHUB_USER=ragauskl:$GITHUB_TOKEN
  - git config --global user.email "$GITHUB_EMAIL"
  - git config --global user.name "$GITHUB_USER"
  - git config user.email "$GITHUB_EMAIL"
  - git config user.name "$GITHUB_USER"
  - git remote set-url origin https://$GITHUB_USER@github.com/ragauskl/portfolio.git

stages:
  - name: build_app
    if: (head_branch = master) OR (head_branch = develop)
  - name: deploy_app
    if: (branch = master) AND (type = push)

jobs:
  include:
    - stage: build_app
      script: cd app && npm run build
    - stage: deploy_app
      script: cd app && npm run build && npm run deploy

branches:
  only:
  - master
  - develop

install:
  - npm i -g @angular/cli
  - cd api
  - npm i
  - cd ../app
  - npm i
  - cd ..

